defmodule Zenith.Repo.Migrations.AddingPhotoHashTeacherStudent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teachers) do
      add :photo_hash, :text
    end

    alter table(:students) do
      add :photo_hash, :text
    end
  end

  def down do
    alter table(:students) do
      remove :photo_hash
    end

    alter table(:teachers) do
      remove :photo_hash
    end
  end
end
