defmodule Zenith.Repo.Migrations.Teste do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lessons) do
      add :attendance_taken, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:lessons) do
      remove :attendance_taken
    end
  end
end
