defmodule Zenith.Repo.Migrations.ScoreIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:scores, [:result_id, :topic_id], name: "scores_score_identity_index")
  end

  def down do
    drop_if_exists unique_index(:scores, [:result_id, :topic_id],
                     name: "scores_score_identity_index"
                   )
  end
end
