defmodule Zenith.Repo.Migrations.AddClassResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:classes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :level, :text, null: false

      add :language_id,
          references(:languages,
            column: :id,
            name: "classes_language_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:classes, "classes_language_id_fkey")

    drop table(:classes)
  end
end
