defmodule Zenith.Repo.Migrations.AddLessonResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lessons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :datetime, :utc_datetime, null: false

      add :teacher_id,
          references(:teachers,
            column: :id,
            name: "lessons_teacher_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :class_id,
          references(:classes,
            column: :id,
            name: "lessons_class_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "lessons_classroom_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:lessons, "lessons_teacher_id_fkey")

    drop constraint(:lessons, "lessons_class_id_fkey")

    drop constraint(:lessons, "lessons_classroom_id_fkey")

    drop table(:lessons)
  end
end
