defmodule Zenith.Repo.Migrations.RelatingExamScore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scores) do
      add :exam_id,
          references(:exams,
            column: :id,
            name: "scores_exam_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :enrollment_id,
          references(:enrollments,
            column: :id,
            name: "scores_enrollment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:scores, "scores_exam_id_fkey")

    drop constraint(:scores, "scores_enrollment_id_fkey")

    alter table(:scores) do
      remove :enrollment_id
      remove :exam_id
    end
  end
end
