defmodule Zenith.Repo.Migrations.PendingMigrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:frequencies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :attendance, :boolean, null: false

      add :lesson_id,
          references(:lessons,
            column: :id,
            name: "frequencies_lesson_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :enrollment_id,
          references(:enrollments,
            column: :id,
            name: "frequencies_enrollment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:frequencies, "frequencies_lesson_id_fkey")

    drop constraint(:frequencies, "frequencies_enrollment_id_fkey")

    drop table(:frequencies)
  end
end
