defmodule Zenith.Repo.Migrations.AddEnrollmentResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:enrollments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :student_id,
          references(:students,
            column: :id,
            name: "enrollments_student_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :class_id,
          references(:classes,
            column: :id,
            name: "enrollments_class_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:enrollments, "enrollments_student_id_fkey")

    drop constraint(:enrollments, "enrollments_class_id_fkey")

    drop table(:enrollments)
  end
end
