defmodule Zenith.Repo.Migrations.AddCascadeDeleteToFrequenciesLesson do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:frequencies, "frequencies_lesson_id_fkey")

    alter table(:frequencies) do
      modify :lesson_id,
             references(:lessons,
               column: :id,
               name: "frequencies_lesson_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:frequencies, "frequencies_lesson_id_fkey")

    alter table(:frequencies) do
      modify :lesson_id,
             references(:lessons,
               column: :id,
               name: "frequencies_lesson_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
