defmodule Zenith.Repo.Migrations.ChangingPhotoKeyColumnName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:teachers), :photo_hash, to: :photo_key

    rename table(:students), :photo_hash, to: :photo_key
  end

  def down do
    rename table(:students), :photo_key, to: :photo_hash

    rename table(:teachers), :photo_key, to: :photo_hash
  end
end
