defmodule Zenith.Repo.Migrations.AddGradeResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:grades, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :enrollment_id,
          references(:enrollments,
            column: :id,
            name: "grades_enrollment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :language_id,
          references(:languages,
            column: :id,
            name: "grades_language_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:grades, "grades_enrollment_id_fkey")

    drop constraint(:grades, "grades_language_id_fkey")

    drop table(:grades)
  end
end
