defmodule Zenith.Repo.Migrations.DeletingStudentEnrollmentCascade do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:enrollments, "enrollments_student_id_fkey")

    alter table(:enrollments) do
      modify :student_id,
             references(:students,
               column: :id,
               name: "enrollments_student_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:enrollments, "enrollments_student_id_fkey")

    alter table(:enrollments) do
      modify :student_id,
             references(:students,
               column: :id,
               name: "enrollments_student_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
